version: "3.8"

services:
  nginx:
    image: ghcr.io/koyashiro/nginx-rtmp:latest
    ports:
      - 80:80
      - 443:443
      - 1935:1935
    volumes:
      - type: bind
        source: nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: allow.conf
        target: /etc/nginx/allow.conf
      - type: bind
        source: fullchain.pem
        target: /etc/nginx/fullchain.pem
      - type: bind
        source: privkey.pem
        target: /etc/nginx/privkey.pem
    restart: always
