services:
  nginx:
    image: ghcr.io/koyashiro/nginx-rtmp:latest
    environment:
      TZ: Asia/Tokyo
    ports:
      - 443:443
    volumes:
      - type: bind
        source: nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: allow.conf
        target: /etc/nginx/allow.conf
      - type: bind
        source: fullchain.pem
        target: /etc/nginx/fullchain.pem
      - type: bind
        source: privkey.pem
        target: /etc/nginx/privkey.pem
    logging:
      driver: json-file
      options:
        max-file: 3
        max-size: 1M
    restart: always
