services:
  nginx:
    image: nginx:latest
    environment:
      TZ: Asia/Tokyo
    ports:
      - 443:443
    volumes:
      - type: bind
        source: nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: volume
        source: lego-data
        target: /etc/lego
    logging:
      driver: json-file
      options:
        max-file: 3
        max-size: 10M
    restart: always

  rtsp-simple-server:
    image: aler9/rtsp-simple-server:latest
    environment:
      TZ: Asia/Tokyo
      RTSP_RTSPDISABLE: true
      RTSP_RTMPADDRESS: :1935
      RTSP_HLSADDRESS: :80
      RTSP_HLSALWAYSREMUX: true
      RTSP_HLSSEGMENTCOUNT: 3
      RTSP_HLSSEGMENTDURATION: 1s
      RTSP_PATHS_ALL_PUBLISHUSER: ${USER}
      RTSP_PATHS_ALL_PUBLISHPASS: ${PASSWORD}
    logging:
      driver: json-file
      options:
        max-file: 3
        max-size: 10M
    restart: always

  lego:
    image: goacme/lego:latest
    environment:
      CLOUDFLARE_EMAIL: ${CLOUDFLARE_EMAIL}
      CLOUDFLARE_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
    volumes:
      - type: volume
        source: lego-data
        target: /etc/lego
    profiles:
      - lego

volumes:
  lego-data:
